name: DevContainer Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the DevContainer image
      run: devcontainer build --workspace-folder . --push true --image-name Kinovea-Companion
