name: Rebuild Slim Container Image
on: # rebuild on slim/Dockerfile changes
  push:
    paths: 
      - .devcontainer/slim/Dockerfile
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASS }}
        
      - name: Build Container Image
        run: docker build . --file .devcontainer/slim/Dockerfile --tag ghcr.io/${{ github.repository_owner }}/kc-devenv 
        
      - name: Push Container Image
        run: docker push ghcr.io/${{ github.repository_owner }}/kc-devenv
