name: Rebuild Container Image
on: # rebuild on any base.Dockerfile or Dockerfile changes
  push:
    branches: [ master ]
    paths: 
      - .devcontainer/base.Dockerfile
      - .devcontainer/Dockerfile
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASS }}
        
      - name: Build and Push Container Image
        uses: devcontainers/ci@v0.2.1900000118
        with:
          imageName: ghcr.io/${{ github.repository }}
          runCmd: cd . # no-op
