name: Rebuild Container Image
on: # rebuild on any .devcontainer changes
  push:
    paths: 
      - .devcontainer/build/Dockerfile
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASS }}
        
      - name: Build Container Image
        run: docker build . --file Dockerfile --tag kc-devenv 
        
      - name: Push Container Image
        run: docker push ${{ github.repository_owner }}/kc-devenv
